const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const defaultGames=[
 {id:'apple-dodge',name:'Apple Dodge',icon:'🍎',path:'games/apple-dodge/index.html',added:Date.now()-3000,desc:'Dodge falling apples and survive.'},
 {id:'neon-click',name:'Neon Click',icon:'⚡',path:'games/neon-click/index.html',added:Date.now()-2000,desc:'Click the target before time runs out.'},
 {id:'memory',name:'Memory Grid',icon:'🧠',path:'games/memory/index.html',added:Date.now()-1000,desc:'Match every pair in as few moves as possible.'},
 {id:'2048-original',name:'2048 Mini',icon:'🔢',path:'games/2048-mini.html',added:Date.now(),desc:'A compact original number puzzle.'}
];
const defaults={tabName:'APPLEBOTTOM UBG',siteName:'APPLEBOTTOM',homeTitle:'APPLEBOTTOM',homeSub:'Your calm little corner of the internet.',gamesTitle:'All games',recentTitle:'Recently added',accent:'#ff334f',cardSize:'medium',dark:true,bg:''};
let cfg={...defaults,...JSON.parse(localStorage.getItem('applebottom_cfg')||'{}')};
let games=JSON.parse(localStorage.getItem('applebottom_games')||'null')||defaultGames;
let editMode=false,currentGame=null,localGameUrl=null;
function save(){localStorage.setItem('applebottom_cfg',JSON.stringify(cfg));localStorage.setItem('applebottom_games',JSON.stringify(games));}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove('show'),1800)}
function apply(){document.documentElement.style.setProperty('--accent',cfg.accent);document.title=cfg.tabName||'APPLEBOTTOM UBG';document.body.classList.toggle('light',!cfg.dark);document.body.classList.remove('card-small','card-large');if(cfg.cardSize==='small')document.body.classList.add('card-small');if(cfg.cardSize==='large')document.body.classList.add('card-large');if(cfg.bg){document.body.classList.add('has-bg');document.documentElement.style.setProperty('--site-bg',`url(${cfg.bg})`)}else document.body.classList.remove('has-bg');$('#brandName').textContent=cfg.siteName;$('#heroName').textContent=cfg.homeTitle;$('#heroSub').textContent=cfg.homeSub;$('#gamesTitle').textContent=cfg.gamesTitle;$('#recentTitle').textContent=cfg.recentTitle;$('#countPill').textContent=games.length;$('#gameCountSide').textContent=games.length;$('#setTabName').value=cfg.tabName;$('#setSiteName').value=cfg.siteName;$('#setHomeTitle').value=cfg.homeTitle;$('#setHomeSub').value=cfg.homeSub;$('#setGamesTitle').value=cfg.gamesTitle;$('#setRecentTitle').value=cfg.recentTitle;$('#setAccent').value=cfg.accent;$('#setCardSize').value=cfg.cardSize;$('#darkToggle').classList.toggle('on',cfg.dark)}
function card(g){const el=document.createElement('article');el.className='game-card';el.innerHTML=`<button class="card-edit" title="Edit">✎</button><div class="thumb">${g.image?`<img src="${g.image}" alt="">`:g.icon||'🎮'}</div><div class="game-info"><div class="game-name">${escapeHtml(g.name)}</div><div class="game-desc">${escapeHtml(g.desc||'Play now')}</div></div>`;el.addEventListener('click',e=>{if(e.target.closest('.card-edit'))return;openGame(g)});el.querySelector('.card-edit').addEventListener('click',e=>{e.stopPropagation();openEditor(g)});return el}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(list=games){$('#recentGrid').innerHTML='';games.slice().sort((a,b)=>b.added-a.added).slice(0,6).forEach(g=>$('#recentGrid').appendChild(card(g)));$('#gamesGrid').innerHTML='';list.forEach(g=>$('#gamesGrid').appendChild(card(g)));$('#countPill').textContent=games.length;$('#gameCountSide').textContent=games.length;}
function renderSearch(q){const term=q.trim().toLowerCase();const result=term?games.filter(g=>g.name.toLowerCase().includes(term)||String(g.desc||'').toLowerCase().includes(term)):games;$('#searchMeta').textContent=`${result.length} game${result.length===1?'':'s'} found`;$('#searchGrid').innerHTML='';result.forEach(g=>$('#searchGrid').appendChild(card(g)))}
function showView(name){$$('.view').forEach(v=>v.classList.add('hidden'));$(`#${name}View`).classList.remove('hidden');$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));$('#pageTitle').textContent=name==='home'?'Home':name[0].toUpperCase()+name.slice(1);window.scrollTo({top:0,behavior:'smooth'});if(name==='search')setTimeout(()=>$('#searchPageInput').focus(),50)}
function openGame(g){currentGame=g;$('#playerTitle').textContent=g.name;$('#gameFrame').src=g.path;$('#gameModal').classList.remove('hidden');document.body.style.overflow='hidden'}
function closeGame(){$('#gameModal').classList.add('hidden');$('#gameFrame').src='about:blank';document.body.style.overflow='';currentGame=null}
function openEditor(g=null){currentGame=g;$('#editorTitle').textContent=g?'Edit game':'Add game';$('#gameNameInput').value=g?.name||'';$('#gameIconInput').value=g?.icon||'🎮';$('#gamePathInput').value=g?.path||'';$('#deleteGameBtn').style.display=g?'block':'none';$('#gameEditor').classList.remove('hidden')}
function closeEditor(){$('#gameEditor').classList.add('hidden')}
function saveEditor(){const name=$('#gameNameInput').value.trim();const path=$('#gamePathInput').value.trim();const icon=$('#gameIconInput').value.trim()||'🎮';if(!name){toast('Enter a game name');return}if(currentGame){Object.assign(currentGame,{name,path:path||currentGame.path,icon,desc:currentGame.desc||'Play now'});toast('Game updated')}else{games.unshift({id:crypto.randomUUID(),name,icon,path:path||'about:blank',added:Date.now(),desc:'Play now'});toast('Game added')}save();apply();render();closeEditor()}
$('#deleteGameBtn').onclick=()=>{if(!currentGame)return;games=games.filter(x=>x.id!==currentGame.id);save();apply();render();closeEditor();toast('Game deleted')};
function bindNav(){$$('.nav').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.nav)));$('#topSearch').onclick=()=>showView('search');$('#topSettings').onclick=()=>showView('settings');$('#browseBtn').onclick=()=>showView('games');$('#recentAll').onclick=()=>showView('games');$('#addGameBtn').onclick=()=>openEditor();$('#addGameSettings').onclick=()=>openEditor();$('#topRandom').onclick=()=>games.length&&openGame(games[Math.floor(Math.random()*games.length)]);$('#topTheme').onclick=()=>{cfg.dark=!cfg.dark;save();apply();toast(cfg.dark?'Dark mode':'Light mode')};}
$('#heroSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){showView('search');$('#searchPageInput').value=e.target.value;renderSearch(e.target.value)}});$('#gamesSearch').addEventListener('input',e=>{const q=e.target.value.toLowerCase();const list=games.filter(g=>g.name.toLowerCase().includes(q)||String(g.desc||'').toLowerCase().includes(q));render(list);$('#gamesEmpty').classList.toggle('hidden',list.length>0)});$('#searchPageInput').addEventListener('input',e=>renderSearch(e.target.value));
$('#playerBack').onclick=closeGame;$('#playerReload').onclick=()=>{const f=$('#gameFrame');f.src=f.src};$('#playerFullscreen').onclick=()=>$('#gameFrame').requestFullscreen?.();$('#playerDownload').onclick=()=>{if(!currentGame)return;const a=document.createElement('a');a.href=currentGame.path;a.download=currentGame.name.replace(/[^a-z0-9]+/gi,'-')+'.html';a.click()};$('#editorClose').onclick=closeEditor;$('#editorCancel').onclick=closeEditor;$('#saveGameBtn').onclick=saveEditor;
$('#setTabName').oninput=e=>{cfg.tabName=e.target.value;save();apply()};$('#setSiteName').oninput=e=>{cfg.siteName=e.target.value;save();apply()};$('#setHomeTitle').oninput=e=>{cfg.homeTitle=e.target.value;save();apply()};$('#setHomeSub').oninput=e=>{cfg.homeSub=e.target.value;save();apply()};$('#setGamesTitle').oninput=e=>{cfg.gamesTitle=e.target.value;save();apply()};$('#setRecentTitle').oninput=e=>{cfg.recentTitle=e.target.value;save();apply()};$('#setAccent').oninput=e=>{cfg.accent=e.target.value;save();apply()};$('#setCardSize').onchange=e=>{cfg.cardSize=e.target.value;save();apply()};$('#darkToggle').onclick=()=>{cfg.dark=!cfg.dark;save();apply()};
$('#bgUpload').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{cfg.bg=r.result;save();apply();toast('Background saved')};r.readAsDataURL(f)};$('#clearBg').onclick=()=>{cfg.bg='';save();apply();toast('Background cleared')};$('#editModeBtn').onclick=()=>{editMode=!editMode;document.body.classList.toggle('edit-mode',editMode);toast(editMode?'Edit mode on':'Edit mode off')};$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({config:cfg,games},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='applebottom-settings.json';a.click();URL.revokeObjectURL(a.href)};$('#resetBtn').onclick=()=>{if(confirm('Reset APPLEBOTTOM settings and custom games?')){localStorage.removeItem('applebottom_cfg');localStorage.removeItem('applebottom_games');location.reload()}};
$('#localGame').onchange=e=>{const f=e.target.files[0];if(!f)return;const url=URL.createObjectURL(f);const g={id:'local-'+Date.now(),name:f.name.replace(/\.html?$/i,''),icon:'📄',path:url,added:Date.now(),desc:'Local game'};games.unshift(g);save();render();apply();toast('Local game added for this browser session')};
$('#gameFileInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const url=URL.createObjectURL(f);$('#gamePathInput').value=url};
let typed='';document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('#gameModal').classList.contains('hidden'))closeGame();if(!$('#gameEditor').classList.contains('hidden'))closeEditor();}if(document.activeElement.tagName!=='INPUT'){typed=(typed+e.key.toLowerCase()).slice(-7);if(typed==='adminme'){editMode=!editMode;document.body.classList.toggle('edit-mode',editMode);toast(editMode?'Edit mode unlocked':'Edit mode locked');typed=''}}});
function clock(){const d=new Date();$('#dateTime').textContent=d.toLocaleString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'})+' — '+d.toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'});setTimeout(clock,1000)}
bindNav();apply();render();clock();
