const games=[["Firefox","🦊"],["Krita","🎨"],["Impossible Quiz 2","❓"],["Scary Teacher 3D","🏫"],["Celeste 64","🏔️"],["Balatro Modded","🃏"],["2048","🔢"],["Adventure","🗺️"],["Astro","🚀"],["Basketball","🏀"],["Block Puzzle","🧩"],["Chess","♟️"],["Clicker","🖱️"],["Cookie Clicker","🍪"],["Crossword","✏️"],["Doodle Jump","⬆️"],["Flappy Bird","🐦"],["Geometry Dash","🔷"],["Hextris","⬡"],["Jetpack","🎒"],["Kart","🏎️"],["Little Alchemy","⚗️"],["Minesweeper","💣"],["Pac-Man","🟡"],["Portal Puzzle","🌀"],["Snake","🐍"],["Solitaire","🃏"],["Space Invaders","👾"],["Tetris","🟦"],["Wordle","🔤"],["World Guessr","🌎"],["Zuma","🔴"]];
const $=x=>document.querySelector(x),$$=x=>document.querySelectorAll(x);
function cards(id,list=games){$(id).innerHTML=list.map(g=>`<div class="card"><div class="thumb">${g[1]}</div><div class="name">${g[0]}</div></div>`).join("")}
cards("#allHome");cards("#allGames");cards("#recent",games.slice(0,6));
function page(n){$$(".page").forEach(x=>x.classList.remove("active"));$(n==="search"?"#searchPage":"#"+n).classList.add("active");$$("nav button").forEach(x=>x.classList.toggle("active",x.dataset.page===n));$("#title").innerHTML=n[0].toUpperCase()+n.slice(1)+' <i>252</i>'}
$$("nav button[data-page]").forEach(b=>b.onclick=()=>page(b.dataset.page));$("#browse").onclick=()=>page("games");$("#heroSearch").onclick=()=>page("search");
$("#settings").onclick=()=>$("#shade").classList.add("open");$("#close").onclick=()=>$("#shade").classList.remove("open");
$$(".swatches button").forEach(b=>b.onclick=()=>document.documentElement.style.setProperty("--accent",b.dataset.c));
$$(".sizes button").forEach(b=>b.onclick=()=>{document.body.classList.remove("small","large");if(b.dataset.s!=="medium")document.body.classList.add(b.dataset.s)});
$("#tabName").oninput=e=>document.title=e.target.value;
$("#searchInput").oninput=e=>{let q=e.target.value.toLowerCase();let a=games.filter(g=>g[0].toLowerCase().includes(q));$("#results").innerHTML=(q?a:[]).map(g=>`<div class="result"><span>${g[1]}</span>${g[0]}</div>`).join("")||'<div class="result">Type a game name to search.</div>'};
document.onkeydown=e=>{if(e.key==="Escape")$("#shade").classList.remove("open")};
function clock(){let d=new Date();$("#date").textContent=d.toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric",year:"numeric"})+" • "+d.toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}clock();setInterval(clock,30000);